[project]
name = "uiowa-aquatics-schedule"
version = "0.1.0"
description = "Scraper for the UIOWA aquatics pool schedule."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "cloudscraper>=1.2.71",
    "tabulate>=0.9.0",
]
